version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/fwea
    restart: always

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5005:80"
    restart: always

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fwea
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  jenkins:
    # If you still need Jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8181:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  postgres_data:
  jenkins_home:
