version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=fwea
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/fwea
      - TZ=Asia/Jakarta # Set time zone for the backend container
    restart: always

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5005:5005"
    restart: always

  postgres:
    image: postgres:13
    ports:
      - "5010:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fwea
      - TZ=Asia/Jakarta # Set time zone for Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      # Add a healthcheck for Postgres
      test: [ "CMD-SHELL", "pg_isready -U postgres -d fwea" ]
      interval: 10s
      timeout: 5s
      retries: 5

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8181:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  postgres_data:
  jenkins_home:
