-- AlterTable
ALTER TABLE "AvDetailLayer" ALTER COLUMN "avDetailUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avDetailIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "AvDetailPremium" ALTER COLUMN "avPremiumUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avPremiumIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "AvDetailShare" ALTER COLUMN "avShareUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avShareIdr" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avSharePremiumUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avSharePremiumIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "LiabilityDetailLayer" ALTER COLUMN "liabilityDetailUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "liabilityDetailIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "LiabilityDetailPremium" ALTER COLUMN "liabilityPremiumUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "liabilityPremiumIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "LiabilityDetailShare" ALTER COLUMN "liabilityShareUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "liabilityShareIdr" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "liabilitySharePremiumUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "liabilitySharePremiumIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "MaDetailLayer" ALTER COLUMN "maDetailUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maDetailIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "MaDetailPremium" ALTER COLUMN "maPremiumUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maPremiumIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "MaDetailShare" ALTER COLUMN "maShareUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maShareIdr" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maSharePremiumUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maSharePremiumIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PdmaDetailLayer" ALTER COLUMN "pdmaDetailUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pdmaDetailIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PdmaDetailPremium" ALTER COLUMN "pdmaPremiumUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pdmaPremiumIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PdmaDetailShare" ALTER COLUMN "pdmaShareUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pdmaShareIdr" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pdmaSharePremiumUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pdmaSharePremiumIdr" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TreatyDetailCurrent" ALTER COLUMN "currentExchange" SET DATA TYPE TEXT,
ALTER COLUMN "currentMaintenance" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TreatyDetailPrior" ALTER COLUMN "priorExchange" SET DATA TYPE TEXT,
ALTER COLUMN "priorMaintenance" SET DATA TYPE DOUBLE PRECISION;
